<table style="width:100%" border="0">
    <col width="20%">
    <col width="60%">
    <col width="20%">
    <tr></tr>
    <tr>
        <th style="text-align:left"><img src="Imagenes/UNAM_logo.jpg" width="150px"></th>
        <th style="text-align:center"><span style="font-size:220%">Espín - Boson</span></th> 
        <th style="text-align:right"><img src="Imagenes/LogoCiencias.jpg" width="170px"></th>
    </tr>
</table>

## Hamiltoniano

In [94]:
Paulix = [0.0 1.0;1 0]
Pauliy = [0.0 -im;im 0]
Pauliz = [1.0 0;0 -1]
Paulip = [0.0 2;0 0]
Paulim = [0.0 0;2 0]
hbar = 1.05457162853e-34

1.05457162853e-34

In [95]:
function creation(n)
    
    a = zeros(n)
    for i in 1:n
        a[i] = sqrt(i)
    end
    
    return diagm(a,-1) #reshape(diagm(a,-1),n,n)
    
end;

In [96]:
a = creation(10)'

11×11 Array{Float64,2}:
 0.0  1.0  0.0      0.0      0.0  0.0      …  0.0      0.0      0.0  0.0    
 0.0  0.0  1.41421  0.0      0.0  0.0         0.0      0.0      0.0  0.0    
 0.0  0.0  0.0      1.73205  0.0  0.0         0.0      0.0      0.0  0.0    
 0.0  0.0  0.0      0.0      2.0  0.0         0.0      0.0      0.0  0.0    
 0.0  0.0  0.0      0.0      0.0  2.23607     0.0      0.0      0.0  0.0    
 0.0  0.0  0.0      0.0      0.0  0.0      …  0.0      0.0      0.0  0.0    
 0.0  0.0  0.0      0.0      0.0  0.0         2.64575  0.0      0.0  0.0    
 0.0  0.0  0.0      0.0      0.0  0.0         0.0      2.82843  0.0  0.0    
 0.0  0.0  0.0      0.0      0.0  0.0         0.0      0.0      3.0  0.0    
 0.0  0.0  0.0      0.0      0.0  0.0         0.0      0.0      0.0  3.16228
 0.0  0.0  0.0      0.0      0.0  0.0      …  0.0      0.0      0.0  0.0    

In [97]:
a'*a

11×11 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0
 0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0
 0.0  0.0  2.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0
 0.0  0.0  0.0  3.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0
 0.0  0.0  0.0  0.0  4.0  0.0  0.0  0.0  0.0  0.0   0.0
 0.0  0.0  0.0  0.0  0.0  5.0  0.0  0.0  0.0  0.0   0.0
 0.0  0.0  0.0  0.0  0.0  0.0  6.0  0.0  0.0  0.0   0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  7.0  0.0  0.0   0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  8.0  0.0   0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  9.0   0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  10.0

In [98]:
a*a'  #En este producto tiene problemas

11×11 Array{Float64,2}:
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0  0.0
 0.0  2.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0  0.0
 0.0  0.0  3.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0  0.0
 0.0  0.0  0.0  4.0  0.0  0.0  0.0  0.0  0.0   0.0  0.0
 0.0  0.0  0.0  0.0  5.0  0.0  0.0  0.0  0.0   0.0  0.0
 0.0  0.0  0.0  0.0  0.0  6.0  0.0  0.0  0.0   0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  7.0  0.0  0.0   0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  8.0  0.0   0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  9.0   0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  10.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0  0.0

In [99]:
function ket(n,m)    
    
    k = zeros(n+1)
    k[m+1] = 1
    
    return k
    
end;

In [100]:
function Hh(n,w0)
    
    a = creation(n)'
    
    hh = kron(eye(2),hbar*w0*(a*a'+0.5*eye(n+1)))
    
    return hh
    
end;

function Hr(n,w0)
    
    a = creation(n)'
    
    hr = kron(Paulip,a)+kron(Paulim,a')
    
    return hr
    
end;

function Ha(n,w0)
    
    a = creation(n)'
    
    ha = kron(Paulip,a')+kron(Paulim,a)
    
    return ha
    
end;

function H(n,w,w0)
    
    g = 2
    
    h = (w/2)*kron(Pauliz,eye(n+1))+Hh(n,w0)+g*Hr(n,w0)+g*Ha(n,w0)
    
    return h
    
end;

In [101]:
H(10,2,2)

22×22 Array{Float64,2}:
 1.0  0.0      0.0      0.0     …   0.0      0.0      0.0      0.0   
 0.0  1.0      0.0      0.0         0.0      0.0      0.0      0.0   
 0.0  0.0      1.0      0.0         0.0      0.0      0.0      0.0   
 0.0  0.0      0.0      1.0         0.0      0.0      0.0      0.0   
 0.0  0.0      0.0      0.0         0.0      0.0      0.0      0.0   
 0.0  0.0      0.0      0.0     …   0.0      0.0      0.0      0.0   
 0.0  0.0      0.0      0.0        10.583    0.0      0.0      0.0   
 0.0  0.0      0.0      0.0         0.0     11.3137   0.0      0.0   
 0.0  0.0      0.0      0.0        11.3137   0.0     12.0      0.0   
 0.0  0.0      0.0      0.0         0.0     12.0      0.0     12.6491
 0.0  0.0      0.0      0.0     …   0.0      0.0     12.6491   0.0   
 0.0  4.0      0.0      0.0         0.0      0.0      0.0      0.0   
 4.0  0.0      5.65685  0.0         0.0      0.0      0.0      0.0   
 0.0  5.65685  0.0      6.9282      0.0      0.0      0.0      0.0